### ISSUE TITLE
install error,under win7 64x,node 12.12

### ISSUE THREAD

**Issue by fullmap** [tom-james-watson/p2p.chat#18]
C:\chat\p2p.chat-master>npm install
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\camelcase-86c84332\package.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\node-sass-f85e1bcc\package.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\signalhub-99cd894b\package.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\sass-loader-5d7b4f78\package.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\camelcase-86c84332\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\node-sass-f85e1bcc\binding.gyp'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\signalhub-99cd894b\.npmignore'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\sass-loader-5d7b4f78\CHANGELOG.md'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\camelcase-86c84332\license'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\node-sass-f85e1bcc\CHANGELOG.md'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\signalhub-99cd894b\README.md'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\sass-loader-5d7b4f78\LICENSE'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-webpack-plugin-85985017\lib\constants.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\camelcase-86c84332\readme.md'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\node-sass-f85e1bcc\LICENSE'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\signalhub-99cd894b\LICENSE'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-webpack-plugin-85985017\lib\lint-dirty-modules-plu
gin.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\node-sass-f85e1bcc\README.md'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\sass-loader-5d7b4f78\README.md'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-webpack-plugin-85985017\lib\linter.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\signalhub-99cd894b\test.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-webpack-plugin-85985017\lib\run-compilation.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\signalhub-99cd894b\server.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\signalhub-99cd894b\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\signalhub-99cd894b\example.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\signalhub-99cd894b\bin.js'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\chat\p2p.chat-master\n
ode_modules\.staging\stylelint-a02b6f81\lib\rules'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\signalhub-99cd894b\app.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\signalhub-99cd894b\Procfile'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\signalhub-99cd894b\.travis.yml'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\json5-e1151893\dist\index.min.mjs'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\rules\atRuleNameSpaceChecker.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\rules\declarationBangSpaceChecker.js'

npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\rules\declarationColonSpaceChecker.js
'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\rules\findMediaOperator.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\rules\functionCommaSpaceChecker.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\rules\functionCommaSpaceFix.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\rules\comment-empty-line-before\index
.js'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\chat\p2p.chat-master\n
ode_modules\.staging\stylelint-a02b6f81\lib\rules\comment-no-empty'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\rules\function-calc-no-invalid\index.
js'
npm WARN tar EPERM: operation not permitted, open 'C:\chat\p2p.chat-master\node_
modules\.staging\stylelint-a02b6f81\lib\rules\function-url-scheme-blacklist\inde
x.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\rules\selector-list-comma-newline-aft
er\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\parseCalcExpression\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isAfterComment.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isAfterSingleLineComment.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isAfterStandardPropertyDeclarat
ion.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isAutoprefixable.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isBlocklessAtRuleAfterBlockless
AtRule.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isBlocklessAtRuleAfterSameNameB
locklessAtRule.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isCounterIncrementCustomIdentVa
lue.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isCounterResetCustomIdentValue.
js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isCustomElement.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isCustomMediaQuery.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isCustomProperty.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isCustomPropertySet.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isCustomSelector.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isFirstNested.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isFirstNodeOfRoot.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isKeyframeRule.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isKeyframeSelector.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isLogicalCombination.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isMathFunction.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isNumbery.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isOnlyWhitespace.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isRangeContextMediaFeature.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isSharedLineComment.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isSingleLineString.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isStandardSyntaxAtRule.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isStandardSyntaxCombinator.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isStandardSyntaxDeclaration.js'

npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isStandardSyntaxFunction.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isStandardSyntaxMediaFeature.js
'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isStandardSyntaxMediaFeatureNam
e.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isStandardSyntaxProperty.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isStandardSyntaxRule.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isStandardSyntaxSelector.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isStandardSyntaxTypeSelector.js
'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isStandardSyntaxUrl.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isStandardSyntaxValue.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isValidFontSize.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isValidHex.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isVariable.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\isWhitespace.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\formatters\jsonFormatter.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\levenshteinDistance.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\matchesStringOrRegExp.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\rules\mediaFeatureColonSpaceChecker.j
s'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\rules\mediaQueryListCommaWhitespaceCh
ecker.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\testUtils\mergeTestDescriptions.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\nextNonCommentNode.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\nodeContextLookup.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\noFilesFoundError.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\optionsMatches.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\chat\p2p.chat-master\no
de_modules\.staging\stylelint-a02b6f81\lib\utils\parseCalcExpression\parser.js'
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/tom-james-watson/
webrtc-swarm.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-06-01T0
9_46_33_539Z-debug.log

C:\chat\p2p.chat-master>

**Comment by tom-james-watson** [comment]
Sorry, windows is not supported.
