### ISSUE TITLE
improve the interface

### ISSUE THREAD

**Issue by Zibri** [tom-james-watson/p2p.chat#2]
This is very nice but the interface kinda sucks.
Unfortunately I am not good with html and css but I think the best interface around is the one implemented by appear.in.
Can you make a similar one?

**Comment by tom-james-watson** [comment]
Hello - the project is still pretty alpha. Nice to see someone stumble across it.

I agree that the interface is pretty basic at the moment. What exactly is it that you think should be improved?

**Comment by roscoevanderboom** [comment]
haha....it's a simple interface...maybe "sucks" is a little harsh. Personally. I like that is very simple. I played a little with the scss and easily redesigned it to be more evenly spaced out. Remove some padding, raise the bottum margin of the "waiting for peers" and "peer-streams" classes. Currently, the video feed is too low in the browser view. but it's an easy fix.

This is a great project!!

**Comment by roscoevanderboom** [comment]
before
![before](https://user-images.githubusercontent.com/39595310/46052267-1d7c8d80-c170-11e8-9287-62226a48584d.png)

after
![after](https://user-images.githubusercontent.com/39595310/46052260-15245280-c170-11e8-919a-48263883068f.png)

**Comment by tom-james-watson** [comment]
The app has been completely rewritten, you might be interested in checking out the new version :)
